name: amity_uikit_beta_service
description: Amity UIkit opensource developed by SLE team to enable social feature in Flutter.
version: 0.2.1
homepage: https://github.com/ThanakornThanom/ThanakornThanom--flutter_amity_uikit_beta_service

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  animation_wrappers: ^3.0.0
  font_awesome_flutter: ^10.1.0
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  modal_bottom_sheet: ^3.0.0
  amity_sdk: ^0.40.0
  provider: ^6.0.3
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  video_player: ^2.4.5
  # extended_image: ^6.2.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  socket_io_client: ^1.0.0
  get_time_ago: ^1.1.5
  shimmer: ^3.0.0
  dio:
  sign_in_with_apple: ^4.1.0
  any_link_preview: ^3.0.1
  linkwell: ^2.0.6
  linkify: ^5.0.0
  flutter_link_previewer: ^3.1.0
  url_launcher: ^6.1.6
  flutter_sticky_header: ^0.6.5
  path_provider: ^2.0.2
  video_thumbnail: ^0.5.3
  mime: ^1.0.4
  file_picker: ^6.0.0
  open_file: ^3.3.2
  flutter_svg: ^2.0.9
  permission_handler: 10.2.0
  intrinsic_dimension: ^0.3.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

  assets:
    - assets/images/IMG_5637.JPG
    - assets/images/fileType/
    - assets/Icons/
    - assets/images/Icon name.png
    - assets/images/user_placeholder.png
    - assets/images/noPostYet.png
    - assets/images/privateIcon.png
    - assets/images/noVideo.png
    - assets/

  fonts:
    - family: Material-Design-Iconic-Font
      fonts:
        - asset: assets/fonts/Material-Design-Iconic-Font.ttf
